"use-client"
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from 'react';
import { filtrarProdutos , buscarProduto, produtosEntradas,} from "../service"
import Image from 'next/image';
import Cards from '../components/Cards';
import Categorias from '../components/Categorias';
import CampoDeBusca from '../components/CampoDeBusca';


export default function Home() {

  const [dadosFiltrados, setDadosFiltrados] = useState(produtosEntradas);
  const [textoBuscaDigitado, setTextoBuscaDigitado] = useState("");

  const [botaoClicado, setBotaoClicado] = useState("Entradas");

  const handleBusca = (textoDigitado) => {
    setTextoBuscaDigitado(textoDigitado);
    textoDigitado.length >= 3 && setDadosFiltrados(buscarProduto(textoDigitado))
  };

  const handleFiltro = (categoria) => {
    setTextoBuscaDigitado("");
    setDadosFiltrados(filtrarProdutos(categoria))
    setBotaoClicado(categoria)
  }

  return (
    <>
      <Head>
        <title>Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      
      </Head>
      <header className="limitar-secao">
        <div className={styles.containerBanner}>
          <h1>RESTAURANT</h1>
          <p>De pratos clássicos a criações surpreendentes.</p>
          <p>Nosso cardápio é um requinte de sabores refinados</p>
        </div>
      </header>
      <main className={styles.container_principal}>
            <Categorias 
            handleFiltro={handleFiltro}
            botaoClicado={botaoClicado}/>

            <CampoDeBusca 
            textoBuscaDigitado={textoBuscaDigitado}
            handleBusca={handleBusca}/>

            <section className={styles.secao_cards}>
                  <div>
                    <h2>Cardápio</h2>
                  </div>

                  <div className={styles.container_cards}>
                      {dadosFiltrados.map((produto) => (
                        <Cards key={produto.id} 
                        produto = {produto}/>
                      )) }
                  </div>
            </section>
      </main>
    </>
  );
}
